export const SDGS: { n: number; name: string; color: string; description: string }[] = [
  { n: 1, name: "No Poverty", color: "#E5243B", description: "End poverty in every form and make sure everyone can meet their basic needs." },
  { n: 2, name: "Zero Hunger", color: "#DDA63A", description: "End hunger, improve nutrition and support sustainable food systems." },
  { n: 3, name: "Good Health", color: "#4C9F38", description: "Promote health and wellbeing, with quality care accessible to everyone." },
  { n: 4, name: "Quality Education", color: "#C5192D", description: "Provide inclusive, equitable education and lifelong learning opportunities." },
  { n: 5, name: "Gender Equality", color: "#FF3A21", description: "End discrimination and give women and girls equal rights and opportunities." },
  { n: 6, name: "Clean Water", color: "#26BDE2", description: "Ensure safe water, sanitation and responsible water management for all." },
  { n: 7, name: "Affordable Energy", color: "#FCC30B", description: "Expand access to reliable, sustainable and affordable modern energy." },
  { n: 8, name: "Decent Work", color: "#A21942", description: "Support inclusive economic growth, decent jobs and fair working conditions." },
  { n: 9, name: "Industry & Innovation", color: "#FD6925", description: "Build resilient infrastructure and encourage sustainable innovation." },
  { n: 10, name: "Reduced Inequalities", color: "#DD1367", description: "Reduce unfair gaps in opportunity, income and participation within and between countries." },
  { n: 11, name: "Sustainable Cities", color: "#FD9D24", description: "Make cities inclusive, safe, resilient and environmentally sustainable." },
  { n: 12, name: "Responsible Consumption", color: "#BF8B2E", description: "Use resources wisely and reduce waste across how we produce and consume." },
  { n: 13, name: "Climate Action", color: "#3F7E44", description: "Act urgently to reduce climate risks and strengthen resilience to change." },
  { n: 14, name: "Life Below Water", color: "#0A97D9", description: "Protect oceans and marine life from pollution, overuse and climate harm." },
  { n: 15, name: "Life on Land", color: "#56C02B", description: "Restore ecosystems and protect forests, land, biodiversity and wildlife." },
  { n: 16, name: "Peace & Justice", color: "#00689D", description: "Build peaceful societies, access to justice and accountable institutions." },
  { n: 17, name: "Partnerships", color: "#19486A", description: "Work together across communities and countries to achieve the goals." },
];
